runtime : nodejs20
instance_class : F1

env_variables:
  #Google Gemini API Keys
  GOOGLE_GEMINI_API_KEY: "AIzaSyD3MNmnXVEmrOxRFp4sIhzWHb1VwaTiStE"

  #Path To Google Credentials :
  GOOGLE_APPLICATION_CREDENTIALS: "./keys/googleOCRKey.json"

  # Firebase Service Account Key
  FIREBASE_SERVICE_ACCOUNT_KEY: "./keys/firebaseAccountKey.json"

  #Port
  PORT: 8080
  #Firebase Config
  FIREBASE_API_KEY: "AIzaSyDzuuTOiiNq9HHJ9sGRsCpMHsIB_drWrUM"
  FIREBASE_AUTH_DOMAIN: "audired-820e0.firebaseapp.com"
  FIREBASE_PROJECT_ID: "audired-820e0"
  FIREBASE_STORAGE_BUCKET: "audired-820e0.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID: "401028140081"
  FIREBASE_APP_ID: "1:401028140081:web:16b491c3051c82ae39d910"
  FIREBASE_MEASUREMENT_ID: "G-RBYM3C85BT"

handlers:
  - url: /.*
    secure : always
    redirect_http_response_code : 301
    script: auto
